root: true
parser: "@typescript-eslint/parser"
plugins:
  - import
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  import/extensions: ["error", "always"]
  "@typescript-eslint/no-unused-vars": "off"
